### ISSUE TITLE
not work with default leave animation

### ISSUE THREAD

**Issue by lpf763827726** [kyvg/vue3-notification#10]
the default animation doesn't work

I use it in vue 3,  the enter is work, but when the duration came, leave animation didn't work, it will disappear in a flash, without excessive effect

Then I try to download your demo, **npm install**, then **npm run dev**, when I try to click the "**CSS animation Success button**", I found the same effect, it will disappear in a flash, without excessive effect.

Is it a BUG or my operation is wrong?

**Comment by kyvg** [comment]
It is a bug. Fixed in 2.3.2 version :)
