### ISSUE TITLE
Notification does not disappear after fade-out

### ISSUE THREAD

**Issue by antbrl** [kyvg/vue3-notification#11]
**Describe the bug**
When a notification fades out using CSS animation, it stays in place with opacity 0, but does not disappear.

This puts up the text selection cursor when hovering on desktop, prevents clicking behind the invisible notification and messes up the notification stacking.

**To Reproduce**
1. Run demo
2. Trigger any notification under CSS animation
3. Click on the notification or wait for it to fade out
4. Notification stays in place, albeit invisible with the problems described above

**Expected behavior**
Notification is expected to disappear after fading out.

**Screenshots**
https://i.imgur.com/C0vVIFA.png

**Desktop:**
 - OS: Arch Linux
 - Browser: Firefox 89.0, Chromium 91.0.4472.101

**Additional context**
Bug introduced in v2.3.2.

**Comment by kyvg** [comment]
Fixed in v2.3.3

**Comment by kyvg** [comment]
I can't test it, because Jest mocking TransitionGroup component and there are no problem with destroy after leave :(

**Comment by antbrl** [comment]
Well it works well now on your demo and my project as well. Thanks for being so quick! :)
