### ISSUE TITLE
Replacing the whole template for a notification doesn't work

### ISSUE THREAD

**Issue by WildChild85** [kyvg/vue3-notification#14]
**Describe the bug**
Like the title says customizing the whole template doesn't work anymore. The attributes slot and slot-scope are deprecated. Please update the documentation.

**Comment by Shadercloud** [comment]
When I use the example in the read me the template does not work:

```<notifications>
  <template #body="props">
    <div class="my-notification">
      <p class="title">
        {{ item.title }}
      </p>
      <button class="close" @click="close">
        <i class="fa fa-fw fa-close"></i>
      </button>
      <div v-html="props.item.text"/>
    </div>
  </template>
</notifications>
```
It gives this error:
```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')```

Then if i remove the` {{ item.title }}` to get it work the `@click="close"` also does not work to close the box.

**Comment by Blakeinstein** [comment]
> Then if i remove the` {{ item.title }}` to get it work the `@click="close"` also does not work to close the box.

the example is incorrect. use `{{ props.item.title }}` and `@click="props.close"`

**Comment by kyvg** [comment]
Updated readme here https://github.com/kyvg/vue3-notification/commit/16fe4a82d0a2b60e1b3e344cbadd2b96e3a504aa

**Comment by Blakeinstein** [comment]
> Updated readme here [16fe4a8](https://github.com/kyvg/vue3-notification/commit/16fe4a82d0a2b60e1b3e344cbadd2b96e3a504aa)

still missing props.close instead of close

**Comment by StounhandJ** [comment]
`@click="props.close"`  it was never corrected to the correct version in the documentation
