### ISSUE TITLE
closeOnClick : false is not working in vue3

### ISSUE THREAD

**Issue by sudhanshuptl** [kyvg/vue3-notification#18]
**Describe the bug**
closeOnClick : false is not working in vue3

**To Reproduce**
1. change the default value of `closeOnClick: false` 
    ```
       notify({
            title: "Tenant Onboarding started 🎉",
            text: `Workflow_id = ${result.data["workflow_id"]} <br />
                   Onboarding update will be sent to your mail id`,
            group: "onboard",
            duration: -1,
            closeOnClick: false,
          });
    ```
2. still in the notification will disappear on click

**Expected behavior**
notification should expire after a given time not the click

**Screenshots**
![image](https://user-images.githubusercontent.com/6737212/147762948-f8b6d186-c70b-424f-9e40-cf609ddbdb54.png)

**Desktop (please complete the following information):**
 - OS: Macos
  - Browser: chrome
 -  chrom Version 96.0.4664.110

**Additional context**

**Comment by kyvg** [comment]
@sudhanshuptl, there is no option `closeOnClick` for `notify`. The option is only available in this way:
```
import { createApp } from 'vue'
import Notifications from '@kyvg/vue3-notification'

const app = createApp({...})
app.use(Notifications, {closeOnClick: false});
```

**Comment by kyvg** [comment]
@sudhanshuptl, there is no options `closeOnClick` in `notify`. The option is only available in this way:
```
 <notifications
   group="foo-css"
   position="bottom left"
   :close-on-click="false"
 />
```

**Comment by sudhanshuptl** [comment]
@kyvg Great it does work, but not properly reflected in the documentation.
