### ISSUE TITLE
Replacing only the data of the currently floating notification without generating a new notification

### ISSUE THREAD

**Issue by JUKOOK** [kyvg/vue3-notification#19]
I am writing an issue to explain my case and get advice to everyone who uses this library.

### Problem
I'm writing a code that notify data in a notification using a custom template (slot).
```js
// custom template
<notifications group="custom-notify" position="bottom right">
  <template #body="props">
      // markup notify display 'name', 'price', 'quantity' from props.item
  </template>
</notifications>

// this.$notify call
this.$notify({
  group: 'custom-notify',
  duration: 3000,
  data: {
    id: '1',
    name: 'A',
    price: 30000,
    quantity: 25,
  } // example data
})

// examples of data (occured randomly)
{
    id: '1',
    name: 'A',
    price: 30000,
    quantity: 25,
},
{
    id: '2',
    name: 'B',
    price: 2000,
    quantity: 3,
},
{
    id: '3',
    name: 'A',
    price: 29990,
    quantity: 3,
},
{
    id: '4',
    name: 'B',
    price: 2500,
    quantity: 100,
}
```

In this case(four example datas),  

If `this.$notify` is called with an interval of 3 seconds or more (longer than the `duration`) in the order of the 4 objects above, the previous notification is cleared by the duration, so a total of 4 notifications will occur.

**However, when `this.$notify` is called 4 times within 3 seconds, I want to initialize(reset) the `duration`(3 seconds) of the notification with the same `name` and change only the `price` and `quantity` of the notification (in the end, only 2 notifications for A and B are displayed.**

I wonder if there are any ways or API option for this.

If not, may I ask for feature support?

Thank you.

**Comment by kyvg** [comment]
Hi, @JUKOOK!

if I understand correctly, you can close notification by `id` and then call `this.$notify` for same `name`
https://github.com/kyvg/vue3-notification#programatically-closing
```
const notificationIdsByName = {}; // or new Map()

this.$notify({
  group: 'custom-notify',
  duration: 3000,
  data: {
    id: '1',
    name: 'A',
    price: 30000,
    quantity: 25,
  } // example data
});
notificationIdsByName['A'] =  '1' // {name: id}

setTimeout(() => {
  this.$notify.close(notificationIdsByName['A']);

  this.$notify({
    group: 'custom-notify',
    duration: 3000,
    data: {
      id: '2',
      name: 'A',
      price: 12300,
      quantity: 2315,
    }
  }) // displayed only 2
   notificationIdsByName['A'] =  '2'
}, 1000);
```

and wrap it in function
```
const notificationIdsByName = {}; // or new Map()

function notifyByName(data) {
  this.$notify.close(notificationIdsByName[data.name]);

  this.$notify({
    group: 'custom-notify',
    duration: 3000,
    data: data
  })

  notificationIdsByName[data.name] =  data.id
}

notifyByName({
    id: '2',
    name: 'B',
    price: 2000,
    quantity: 3,
})
notifyByName({
    id: '4',
    name: 'B',
    price: 2500,
    quantity: 100,
})
// should display only '4'
```

Or you could create separate notification groups for each `name` with `max` = 1. It should destroy previous notification when you call `$notify`. 
```
// custom template
<notifications group="custom-notify-a" max="1" position="bottom right">
  <template #body="props">
      // markup notify display 'name', 'price', 'quantity' from props.item
  </template>
</notifications>
<notifications group="custom-notify-b" max="1" position="bottom right">
  <template #body="props">
      // markup notify display 'name', 'price', 'quantity' from props.item
  </template>
</notifications>

this.$notify({
  group: 'custom-notify-a',
  duration: 3000,
  data: {
    id: `'1',`
    price: 30000,
    quantity: 25,
  } // example data
})

setTimeout(() => {
  this.$notify({
    group: 'custom-notify-a',
    duration: 3000,
    data: {
      id: '2',
      price: 12300,
      quantity: 2531,
    }
  })
  // displayed only 2
}, 1000);
```

But there is no API to update currently displayed notification. But I could add it if you need

**Comment by JUKOOK** [comment]
@kyvg 
Thank You So much.

Among the methods you suggested, Set a group for each name and setting `max = 1` is considered difficult because there are more than hundreds of possible item(name) in my case.

But `this.$notify.close(notificationIdsByName['A']);` was very helpful to me, and it works charmingly.

Thanks again for your help!!
