### ISSUE TITLE
Usage with <script setup/>

### ISSUE THREAD

**Issue by nicolasbinet** [kyvg/vue3-notification#23]
**Describe the bug**
When using the `<script setup/>` syntax, the this.$notify is not recognized.

**To Reproduce**
1. Installed @kyvg/vue3-notification, ^2.3.4
2. Added
```
import Notifications from '@kyvg/vue3-notification'
app.use(Notifications)
```
3. Added
`<notifications/>`
4. Getting
`ReferenceError: $notify is not defined`

**Expected behavior**
Is there a way to reference $notify, or should I `import { notify } from "@kyvg/vue3-notification";` ?

**Desktop/Smartphone (please complete the following information):**
 - OS: All
 - Browser All
 - Version 2.3.4

**Additional context**

**Comment by kyvg** [comment]
Hi! There are no `this` when you use `<script setup/>`.

> Is there a way to reference $notify, or should I import { notify } from "@kyvg/vue3-notification"; ?

 Yes, you should use ` import { notify } from "@kyvg/vue3-notification";` :)

**Comment by nicolasbinet** [comment]
@kyvg Thanks for your reply and that's what I finally did.
I was expecting a behavior like `vue-final-modal` that even with `<script setup/>` allow to use a global `$vfm` object that would the equivalent of `$notify`. But it doesn't work as expected, hence my message.
