### ISSUE TITLE
How to bind current components's context to notification?

### ISSUE THREAD

**Issue by Glarionov** [kyvg/vue3-notification#25]
I need to do some actions after clicking on notice, but I don't know hod to do this.

It would be greate if I could use something like this
```
this.$notify(message).bind(this);
```

**Comment by kyvg** [comment]
Hi! You can use custom notification `body` and add click handler on it

```
<notifications
  group="foo"
>
  <template #body="{ item }">
    <div @click="doSmth()">item.data</div>
  </template>
</notifications>
```
