### ISSUE TITLE
return object with id when creating notification

### ISSUE THREAD

**Issue by bilik-tomas** [kyvg/vue3-notification#26]
**Is your feature request related to a problem? Please describe.**
I need to pair id of notification object when the object is created to block closeOnClick, but i dont know when the notification dissapear.
If you get the id of object when created, then you just check if is equal to id emitted by destroy event.

**Describe the solution you'd like**
In the chapter before.

**Describe alternatives you've considered**
Another alternative is implement properties closeOnClick, pauseOnHover and so on. to a single instance (not whole component)

**Additional context**

**Comment by kyvg** [comment]
Hi! 
If you mean something like that...
```javascript
const {id} = this.notify({text: 'foo'})
this.notify.close(id)
```
...you can use your own notification id:
https://github.com/kyvg/vue3-notification#programatically-closing

If you mean something else provide some examples, please :)

**Comment by bilik-tomas** [comment]
Hmm, i didnt notice that i can pass my own id as a object property...
Thank you for your reply.
