### ISSUE TITLE
Does not work in the production of the vite 

### ISSUE THREAD

**Issue by alexis-karyavin** [kyvg/vue3-notification#27]
Please help, when I make a Vite build and send it to prod, it does not work

**Comment by kyvg** [comment]
Hi! Please send more information about packages version and configuration

**Comment by alexis-karyavin** [comment]
"dependencies": {
    "@kyvg/vue3-notification": "^2.3.6",
    "@popperjs/core": "^2.11.2",
    "@vitejs/plugin-vue": "^2.3.3",
    "@vuelidate/core": "^2.0.0-alpha.41",
    "@vuelidate/validators": "^2.0.0-alpha.29",
    "axios": "^0.26.0",
    "bootstrap": "^5.1.3",
    "gridjs": "^5.0.2",
    "nanoid": "^3.3.4",
    "pinia": "^2.0.14",
    "swiper": "^8.0.6",
    "tabulator-tables": "^5.1.0",
    "vite": "^2.9.9",
    "vue": "^3.0.0",
    "vue-i18n": "^9.1.9",
    "vue-imask": "^6.4.2",
    "vue-multiselect": "^3.0.0-alpha.2",
    "vue-router": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "eslint": "^8.17.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^8.7.1",
    "prettier": "^2.2.1",
    "sass": "^1.49.7",
    "vite-plugin-dynamic-import": "^0.9.6",
    "vite-svg-loader": "^3.3.0"
  }

**Comment by alexis-karyavin** [comment]
I call the method in the file where fetch to the server is implemented

<img width="628" alt="Снимок экрана 2022-08-11 в 10 46 42" src="https://user-images.githubusercontent.com/34441593/184087643-68918d83-2d73-410a-aae2-68201e4eed78.png">

This is what the component looks like in app.vue
<img width="726" alt="image" src="https://user-images.githubusercontent.com/34441593/184087787-6a0d8ec8-5b9e-4a2e-a3cf-1c95694a73d9.png">

**Comment by azazely85** [comment]
same problem

**Comment by kyvg** [comment]
@alexis-karyavin @azazely85 it's looks like conflict `vue@~3.0.0` with `vue@^3.0.0`. I tried to fix it in `@kyvg/vue3-notification@2.4.0` version
