### ISSUE TITLE
Runtime errors with Content Security Policy

### ISSUE THREAD

**Issue by DanielBickler** [kyvg/vue3-notification#30]
**Describe the bug**
vue3-notification is not working with a restrictive Content Security Policy.

Our Content Security Policy is "default-src 'self'; object-src 'none';" and at runtime we are getting errors and vue3 notifcations is not working correctly because the CSS Class vue-notification-group is missing. It seems to be trying to add it in an inline/eval fashion that our CSP does not allow.

Locally we allow unsafe-inline/unsafe-eval in our CSP so it works. In the deployed version we have the more restrictive CSP.

We're using Vite 2.9.13, Vue 3.2.37 and @kyvg/vue3-notification 2.4.1.

Are we doing something wrong in how we include / use vue3-notification that is breaking under a restrictive CSP?

**Screenshots**
![image](https://user-images.githubusercontent.com/39422037/193324534-ae66b7f7-8f4a-47eb-9ddc-88a0260a32a0.png)

**Comment by kyvg** [comment]
Hi! That library haven't any eval/inline code. Are you sure that problem with that library?

**Comment by MichalKrakow** [comment]
Hi there, just bump on the very same thing. so... havent yet dived into the source code but what vite spits out in build it's like pure css in js: 
```
.vue-notification-group {
  display: block;
  position: fixed;
  z-index: 5000;
}
.vue-notification-wrapper {
  display: block;
  overflow: hidden;
//  ... and so on
  ````
From what i can tell this is just part of single file component 'Notification.vue' style part. This is where error originates. So should we use some other import method.

Dividing source code so developers can import js and styles seperatly helps with CSP greatly by allowing to place relevant js and css code to respective files on localhost wchich gets loaded with CSP safty policies.

Dont know if theres a way to import your's super nice notifications in such manner. 'Sweet allert' is cinda fat on code size side but for now it's a valid alternative (to whomever stumbless upon this response).

**Comment by MichalKrakow** [comment]
Follow up, this might get bypassed by pushing nonce to the injected style block. This CSP thing is going to burn a lot of money in the industry, really curious if its worth the hussle.

**Comment by kyvg** [comment]
@MichalKrakow I think we can import .css files separately like that, but it would be a breaking change

```javascript
import { createApp } from 'vue'
import Notifications from '@kyvg/vue3-notification'

import '@kyvg/vue3-notification/dist/style.css'

const app = createApp({...})
app.use(Notifications)
```

**Comment by DanielBickler** [comment]
Personally I would have no problem with that breaking change - a lot of Vue 3 libraries need CSS to be included like that, I think it might be the default in Vite?
