### ISSUE TITLE
Styles and position won't work in 2.6.0

### ISSUE THREAD

**Issue by Klavionik** [kyvg/vue3-notification#33]
**Describe the bug**
Notifications apper unstyled and don't respect `position` prop when using version 2.6.0. It's all good when I use 2.5.0.

**To Reproduce**
1. Create a new Vue 3 project using `npm init vue@latest` (choose TypeScript support).
2. Install the latest version of the library (2.6.0)
3. Use `Notifications` plugin and add `notifications` component to the app. Set `position` prop to "top center", for example.
4. Call `notify` to see the notification appears in the top right corner unstyled (see screenshot).

**Expected behavior**
A styled notification to appear in the top center position.

**Screenshots**
This is 2.6.0:
![Screenshot from 2022-11-01 00-34-09](https://user-images.githubusercontent.com/56698047/199114881-9d0cd1e9-2cf3-41ee-8456-80f1f9d212b1.png)

And this is 2.5.0:
![Screenshot from 2022-11-01 00-38-41](https://user-images.githubusercontent.com/56698047/199115415-73736ae4-b2d1-4164-94b4-8a14273fd57b.png)

**Additional context**
I didn't check any another props, maybe they're not working too.

**Comment by kyvg** [comment]
Hi, sorry for that. Fixed in 2.6.1
