### ISSUE TITLE
Can't use when Vue Options API is disabled

### ISSUE THREAD

**Issue by axelkennedal** [kyvg/vue3-notification#37]
**Describe the bug**
In a project with Webpack where the Vue Options API is disabled, this library does not work. It builds, but no notifications pop up.

**To Reproduce**
1. In a project using Webpack, disable the Vue Options API: (set it to `false`, not `true `like this screenshot)
![image](https://user-images.githubusercontent.com/8863787/210213874-4993bc5e-65ee-43e0-b5f0-af3eadd6d471.png)
1. Follow the instructions in the README of this GitHub repo for using the composition API
1. Run Webpack
2. Try to show a notification

**Expected behavior**
A notification should show up.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108

**Smartphone (please complete the following information):**
 N/a

**Additional context**
N/a

**Comment by axelkennedal** [comment]
@kyvg

**Comment by axelkennedal** [comment]
Why was this closed without any comment?

**Comment by kyvg** [comment]
@axelkennedal, Hi!
That library was written with Options API, so it can't work with `__VUE_OPTIONS_API__: false` flag

**Comment by kyvg** [comment]
I rewrote this library to Composition API, now it should work with disabled Options API flag
