### ISSUE TITLE
Problem with laravel sail and vite, "permission denied" on non-existing directory

### ISSUE THREAD

**Issue by Glarionov** [kyvg/vue3-notification#38]
I'm using vue3 with laravel sail and vite, after installing this package, my "sail npm run dev" command prints an error
```
error when starting dev server:
Error: EACCES: permission denied, unlink '/var/www/html/node_modules/.vite/deps/@inertiajs_inertia-vue3.js'
    at unlinkSync (node:fs:1780:3)
    at _unlinkSync (node:internal/fs/rimraf:214:14)
    ...
```
I  tried to chmod that directory, but I don't even have directory "www" inside my "var" directory, so there is nothing to change.
What can I do to make it work?

My versions:
```
        "vite": "^4.0.0",
        "vue": "^3.2.41"
        "@kyvg/vue3-notification": "^2.7.0"
```

**Comment by noook** [comment]
I'm not sure this is linked to this library. The message shows the library but perhaps it's just a coincidence and this library is just the first on which this error occurs.

I don't know sail at all, but `/var/www/html` is quite a regular folder for an app to be deployed on the server so maybe this is a default value for an option.

**Comment by Glarionov** [comment]
@noook 
This error happens when I install this package and is gone when I uninstall this package.
