### ISSUE TITLE
Notification Start Event

### ISSUE THREAD

**Issue by VladimirVagner** [kyvg/vue3-notification#39]
I always get upset when developing a custom notification I can subscribe to the @destroy event, but there is no emit @start. Please add emit, it will help to configure notifications more flexibly or tell me how I can solve my problem? Thanks
![изображение](https://user-images.githubusercontent.com/42632865/212468581-cdf59805-e86e-4990-b066-99246d02b71f.png)

**Comment by kyvg** [comment]
added [here](https://github.com/kyvg/vue3-notification/commit/1b7aa3ca0eceb7c47dd550088ec87d76bf92752a)
