### ISSUE TITLE
Issue when building app 

### ISSUE THREAD

**Issue by giuliaSan** [kyvg/vue3-notification#40]
Since today, using the Component inside my Vue3 app gives me this error
**_You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders_**

I'm using Vue3, Vite, Babel

**Comment by nd9600** [comment]
Me too, it's failing on `t.type ?? ""` in
```
notifyClass(t) {
      return [
        "vue-notification-template",
        this.classes,
        t.type ?? ""
      ];
    },
```

**Comment by Lou117** [comment]
Hi there, same here ; it happened just after a `npm update`, and unable to "rollback" to a previous working state after that... I bet this has nothing to do with `vue3-notification` package, since last release is pretty old...

First who has a solution wins the right to post an update here! :)

**Comment by nd9600** [comment]
@Lou117 I think this is the same problem as in https://github.com/PaulLeCam/react-leaflet/issues/883, if you put `"@kyvg/vue3-notification": "2.7.0"` in your dependencies, that should fix it.

**Comment by Lou117** [comment]
> @Lou117 I think this is the same problem as in [PaulLeCam/react-leaflet#883](https://github.com/PaulLeCam/react-leaflet/issues/883), if you put `"@kyvg/vue3-notification": "2.7.0"` in your dependencies, that should fix it.

Fixed, indeed, thanks!

**Comment by kyvg** [comment]
https://github.com/kyvg/vue3-notification/commit/6c6dce527619750570e6a32bf4ae91d53767099a
