### ISSUE TITLE
Install via CDN Help

### ISSUE THREAD

**Issue by authcompanion** [kyvg/vue3-notification#45]
**Describe the bug**
Hello, thanks for the help. I'm looking to install vue3-notification via CDN like in the jsfiddle example below, but I am unable to see a notification. 

**To Reproduce**
See jsfiddle example [here](https://jsfiddle.net/09rwuvtd/1/)

Is this install correct? Is this approach even supported? 
Thanks for the information.

**Comment by kyvg** [comment]
First of all, we should render our `<notification/>`. We can use render function [h()](https://vuejs.org/api/render-function.html#h) and resolve notification component with [resolveComponent()](https://vuejs.org/api/render-function.html#resolvecomponent). 
Then we should place `notify` function in `onMounted` hook
Something like [that](https://jsfiddle.net/eofa38td/33/). But I still get some internal errors. So, I don't really know how to use it with CDN now :(
