### ISSUE TITLE
Two different groups, same position

### ISSUE THREAD

**Issue by drblaui** [kyvg/vue3-notification#46]
**Is your feature request related to a problem? Please describe.**
When having two (or more) groups display at the same position (e.g. top right), the groups overlap when they are shown at the same time. This makes it hard to use different notification layouts that display at the same position

**Describe the solution you'd like**
Have the two groups behave like they are in the same group and just be displayed under each other

**Describe alternatives you've considered**
Using classes and DOM Manipulation. But that would be very dirty

**Comment by kyvg** [comment]
Hi! It's really complicated feature with current code base. But now you can provide some flags in 'data' and use v-if directive to show different 'body' templates. I think it's not too dirty solution

**Comment by kyvg** [comment]
```vue
<template>
  <notifications>
    <template #body={ data }>
      <foo-notification-type v-if="data.type === 'foo'" />
      <bar-notification-type v-if="data.type === 'bar'" />
    </template>
  </notifications> 
</template>

<script setup>
import { useNotification } from "@kyvg/vue3-notification";

const { notify } = useNotification()

notify({
  title: "Foo notification!",
  data: {
    type: "foo"
 }
});

notify({
  title: "Bar notification!",
  data: {
   type: "bar"
 }
});
</script>
```

Looks clean) I think it would be exactly same way if we make it "native"

**Comment by drblaui** [comment]
This is perfect, thank you very much!
