### ISSUE TITLE
Tags were removed

### ISSUE THREAD

**Issue by tropee-moein** [kyvg/vue3-notification#48]
Looks like lots of recent tags have been removed. Specifically latest tag which is 2.9.0 is not in the list anymore.

**Comment by FrancescoBallini** [comment]
> Looks like lots of recent tags have been removed. Specifically latest tag which is 2.9.0 is not in the list anymore.

npm also fails when I try to install the latest version of the package, since it is no longer present in the npm registers.

**Comment by tropee-moein** [comment]
Here is a hack we did for now until tags are back (we use yarn 2)
```
yarn remove @kyvg/vue3-notification 
yarn add '@kyvg/vue3-notification@https://github.com/kyvg/vue3-notification#09ceaeb0acb1bc618c4ada625ef59895ffe61ad6'
```
The commit hash is the commit 1.9.0 tag was introduced to master

**Comment by moein** [comment]
as @kyvg said the issue wasn't with this library and we also started getting the error with many others. Closing this issue now

**Comment by tropee-moein** [comment]
as @kyvg said the issue wasn't with this library and we also started getting the error with many others. Closing this issue now
