### ISSUE TITLE
Add parameters position and width to API

### ISSUE THREAD

**Issue by ikreb7** [kyvg/vue3-notification#50]
**Is your feature request related to a problem? Please describe.**

I want to define the attributes ``position`` and ``width`` with a API call. Sadly, it will be ignored.

```
notify({
  title: "Important message!",
  text: "Hello user!",
  position: "top left",
  type: "error",
  width: "400", 
});
```

**Describe the solution you'd like**
If would be nice, if I could use it like the example above.

**Describe alternatives you've considered**
Another solution would be at least to define the parameter global like:

```
app.use(Notifications, { width: "400", postion: "top left" }, { velocity });
```

**Comment by kyvg** [comment]
You can use separate groups if you need just a few position/width combination

```vue
<notification group="top-left-group" position="top left" width="200" />
<notification group="bottom-right-group" position="bottom right" width="400" />
```

```typescript
notify({
  title: "Important message!",
  text: "Hello user!",
  group: "top-left-group"
});

notify({
  title: "Important message!",
  text: "Hello user!",
  group: "bottom-right-group"
});
```
