### ISSUE TITLE
Notifications not working when provided via vue plugin after version 2.4.1 

### ISSUE THREAD

**Issue by silviu-negoita** [kyvg/vue3-notification#51]
**Describe the bug**
Notifications library not working when installed from plugin.

**To Reproduce**
I have a plugin used crossed multiple apps, where some common code is extracted. Along with others, I wanted to also extract Notifications library, with some custom styling. Everything worked seamless including version `2.4.1`, but after that, notifications are not shown at all. If I move the notification out of the plugin and install it in my SPA, works normally.

What could be? I can provide more info if it is needed.

**Comment by kyvg** [comment]
As I remember, there was no any breaking changes between `2.4.1` and `2.9.1`
You can send messages from the developer console if you have any. If not, please provide some minimal configuration to reproduce
