### ISSUE TITLE
Title wrongly rendered from item.timer when item.dangerouslySetInnerHtml is set

### ISSUE THREAD

**Issue by lehni** [kyvg/vue3-notification#52]
The reason is in this faulty line of code, probably an auto-complete error:

https://github.com/kyvg/vue3-notification/blob/649d936fc923ec53aba8df8f853246bfb3cd4bab/src/components/Notifications.vue#L37

**Comment by kyvg** [comment]
Hi! Thank you for your pr
I'll release it as soon as possible
