### ISSUE TITLE
Failed to resolve import "@kyvg/vue3-notification" from "src\main.js". Does the file exist?

### ISSUE THREAD

**Issue by Yan-pi** [kyvg/vue3-notification#54]
**Describe the bug**
I am experiencing an issue when trying to import the `@kyvg/vue3-notification` library. The error message I am receiving is: "Failed to resolve import "@kyvg/vue3-notification" from "src\main.js". Does the file exist?" It seems to be an import error, but I have followed the documentation for importing the library.

**To Reproduce**
(Its a private Repo that i cannot share)

1. I Clone the project from te repository link.
2. Navigated to 'src\main.js' where the import statement for `@kyvg/vue3-notification` is located.
3. Ensured that the other developers have installed the library as per the documentation.
4. Runned the project using Vite command "npm run dev".
5. Observe the error mentioned above.

**Expected behavior**
I expected the library `@kyvg/vue3-notification` to be imported without any issues, as per the documentation.

**Screenshots**
![image](https://github.com/kyvg/vue3-notification/assets/102800044/0f629fca-953a-415a-895c-0f7b57025bfb)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Node.js Version: [20.4.0]
 - Vite Version: [4.1.4]
 - Browser [Chrome]
 - Browser Version [116.0.5845.188 ]

**Additional context**
I recently migrated to this project and encountered this issue when trying to work with the `@kyvg/vue3-notification` library. I have followed the import instructions provided in the library's documentation, but I am still facing this problem. Please let me know if there is any additional information needed to resolve this issue.

**Comment by kyvg** [comment]
Hi! I'm not sure about your first step. What do you mean "clone repository"? Where you clone it? 

By the way, it's better to install it with package manager like npm or yarn. If you want to clone repository and use this library just locally, you should use relative import like

**Comment by Yan-pi** [comment]
Thank you, I used yarn and changed the imports for relative imports :)
