### ISSUE TITLE
Add a mention of the possibility of using with nuxt3

### ISSUE THREAD

**Issue by windx-foobar** [kyvg/vue3-notification#56]
**Is your feature request related to a problem? Please describe.**
No implementation for nuxt3

**Describe the solution you'd like**
I implemented my solution to use this package in nuxt3 environment. Could add a link to README.MD for people who want to use this with nuxt3.

**Additional context**
My contacts:
[telegram](https://t.me/tyominomi)

My package:
[npmjs](https://www.npmjs.com/package/nuxt3-notifications)
[github](https://github.com/windx-foobar/nuxt3-notifications)

**Comment by lavrentev18** [comment]
thanks
its helpful
