### ISSUE TITLE
Typescript support for Component props

### ISSUE THREAD

**Issue by natac13** [kyvg/vue3-notification#57]
**Is your feature request related to a problem? Please describe.**
Yes there is no typescript support for intellisense on the component props and no help found in the README

**Describe the solution you'd like**
I would like to add the following instructions to the README.md file

```ts
import type { FunctionalComponent } from 'vue';
import type { NotificationsOptions } from '@kyvg/vue3-notification';
declare module 'vue' {
  export interface GlobalComponents {
    Notifications: FunctionalComponent<NotificationsOptions>;
  }
}
```

**Describe alternatives you've considered**
Being able to import the `Notifications` component as a _named_ import

**Additional context**
This will give syntax highlighting as well as typescript intellisense

![Screenshot 2023-11-28 at 9 03 40 AM](https://github.com/kyvg/vue3-notification/assets/10660283/cf28201c-3c6c-409a-93ad-fb286bc41b9a)

**Comment by kyvg** [comment]
Now you can type it manually:
`import { Notifications } from '@kyvg/vue3-notification'`
Or, you can use `unplugin-vue-components` resolver 🎉
