### ISSUE TITLE
Previous notifications are not animated to their new position

### ISSUE THREAD

**Issue by sebastiaanluca** [kyvg/vue3-notification#65]
**Describe the bug**
When there's a notification shown and a new notification is added, the previous notification is moved one position **without animation** and the new one is animated in.

This happens with both the CSS and velocity-animate library.

**To Reproduce**
1. Display a notification using `notify()`
2. Add another one using `notify()`

**Expected behavior**
As shown in the GIF in the README, both animations should move to their new position with the configured animation.

**Screenshots**
A short clip:
https://github.com/kyvg/vue3-notification/assets/711940/6f958eec-05fd-473f-a3a9-bc5cdb71105d

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox Developer Edition
 - Version: 124

**Additional context**
`"@kyvg/vue3-notification": "^3.1.4"`

**Comment by kyvg** [comment]
It looks like you're using custom styles or the `animation-name` property. 
- If you're using the `animation-name` property, make sure you've added a CSS `transition`.
- If you're using just custom styles, ensure you don't incorrectly override the following selectors: `.vn-fade-enter-active`, `.vn-fade-leave-active`, and `.vn-fade-move`

**Comment by sebastiaanluca** [comment]
This is a stripped down version of what we're using in our Vue layout. I got the gist of the animation from an old issue in the repository, as it wasn't clear how to name the CSS transitions and how they should look.

The CSS animation here works well for the in and out slide, but not when another notification is added and it's shifting a position. That happens instantly without animation. Perhaps I'm missing an obvious conflict.

```vue
<template>
    <Notifications
        position="bottom right"
        width="min(100%, 420px)"
        class="mb-2 transition-all duration-700 ease-in-out"
        animation-type="css"
        animation-name="toast"
        :pause-on-hover="true"
        :max="3"
    >
        <template #body="{ item: { type, text }, close }">
            <div class="px-2 py-1" :aria-describedby="type" data-testid="toast">
                <div class="shadow-xl rounded-md border border-primary-dark/10 min-h-16 px-4 py-2 flex items-center">
                    <div class="flex-shrink-0">
                        <svg
                            class="h-5 w-5"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            aria-hidden="true"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                                clip-rule="evenodd"
                                data-testid="toast--default__icon"
                            />
                        </svg>
                    </div>
                    <div class="ml-3">
                        <p class="text-sm font-semibold" data-testid="toast__text">
                            {{ text }}
                        </p>
                    </div>
                    <div class="ml-auto pl-3">
                        <button class="rounded-md inline-flex p-1.5 bg-transparent text-primary-light transition duration-150 | hover:bg-primary-dark/5" @click="close">
                            <span class="sr-only">{{ $t('Dismiss') }}</span>
                            <svg
                                class="h-4 w-4"
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 20 20"
                                fill="currentColor"
                                aria-hidden="true"
                            >
                                <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>
        </template>
    </Notifications>
</template>

```

```css
.vue-notification-wrapper {
    /* Properly render shadows */
    overflow: visible !important;
}

.toast-enter-from {
    @apply translate-y-full opacity-0;
}

.toast-enter-to {
    @apply translate-y-0 opacity-100;
}

.toast-leave-from {
    @apply translate-y-0 opacity-100;
}

.toast-leave-to {
    @apply -translate-y-full opacity-0;
}
```

**Comment by sebastiaanluca** [comment]
I've tried to reproduce the issue in a codesandbox, but quickly run into another issue when setting it up following the readme:

![Screenshot 2024-03-13 at 21 23 28](https://github.com/kyvg/vue3-notification/assets/711940/6c834f26-014c-4331-99c8-5c5e05008e83)


https://codesandbox.io/p/devbox/notification-bug-1-5x2lx6
