### ISSUE TITLE
this.$notify() does not work

### ISSUE THREAD

**Issue by rFranzr** [kyvg/vue3-notification#70]
**Describe the bug**
I am currently upgrading an application from Vue2 to Vue3. So we extensively use `this.$notify()` to create notifications.

Unfortunately, I am getting the error `this.$notify is not a function`. I assume it is not correctly registered.
The `notify()` function works.

**To Reproduce**
Basic code to reproduce the error: https://playcode.io/2035071
Find the deployed code here: https://2035071.playcode.io/

Click on the button and watch the browser console.

**Expected behavior**
Notification is correctly sent

**Desktop (please complete the following information):**
 - Linux Manjaro with Firefox

**Comment by kyvg** [comment]
Hi! Try to use this code
```js
import Notifications from "@kyvg/vue3-notification";
app.use(Notifications)
```
instead of this
```js
import { useNotifications } from "@kyvg/vue3-notification";
app.use(useNotifications )
```

**Comment by rFranzr** [comment]
Hi @kyvg, you are right; importing it without the curly braces did the trick.

In my code I was importing it like this `import { Notifications } from "@kyvg/vue3-notification";` :facepalm:
