### ISSUE TITLE
The problem with pauseonhover is with multiple impressions.

### ISSUE THREAD

**Issue by woe10116** [kyvg/vue3-notification#71]
**Describe the bug**
I have specified the pauseonhover property for my notifications. When I call notifications in a row, I want it to pause when I hover over a specific notification, but this does not happen. For example, I have 3 notifications displayed at the same time, I hover over the second one, but the first notification is paused. At the same time, when the 2nd and 3rd notifications disappear, the first one will not disappear, I need to visit it again and only then it will disappear.

my component
![image](https://github.com/user-attachments/assets/dbfec5f9-c1b3-45b1-bc56-526c7a791afc)

**For playback**. 1. Call several notify() 2. Target the third one, for example. 3. Wait for the show to finish

**Expected behavior** The notification I pointed at should be paused.

![image](https://github.com/user-attachments/assets/8d4c3b81-05b4-42b7-969d-c3cabded696d)

**Comment by kyvg** [comment]
Hi, @woe10116! Thanks for the report. I found the problem with timer and fixed it. Fix will be available in the next release :)
