### ISSUE TITLE
How use Confirm notification ?

### ISSUE THREAD

**Issue by bombkiml** [kyvg/vue3-notification#72]
![image](https://github.com/user-attachments/assets/19324905-d8c0-4f04-94bf-80a878b7b5fa)

You have feature Confirm notify ?
I want to use "Confirm" button in notification box alert.

**Comment by kyvg** [comment]
There is no Confirm button feature but you can do I easily using custom body:

```vue
<notifications :close-on-click="false">
  <template #body="{ close, item }">
      <span>
        {{ item.title }}
      </span>

      <button @click="close">
        Confirm
      </button>
    </div>
  </template>
</notifications>
```
