### ISSUE TITLE
error  in ./node_modules/@kyvg/vue3-notification/dist/index.esm.js

### ISSUE THREAD

**Issue by thelittlewozniak** [kyvg/vue3-notification#8]
**Describe the bug**
I just installed the Notification module and I got this

error  in ./node_modules/@kyvg/vue3-notification/dist/index.esm.js

Module parse failed: Unexpected token (334:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         pauseTimeout() {
|             if (this.pauseOnHover) {
>                 this.timerControl?.pause();
|             }
|         },

 @ ./src/main.js 13:0-52 28:8-21
 @ multi (webpack)-dev-server/client?http://192.168.1.34:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**To Reproduce**
npm install --save @kyvg/vue3-notification
Add dependencies to your main.js:

import { createApp } from 'vue'
import Notifications from '@kyvg/vue3-notification'

const app = createApp({...})
app.use(Notifications)
Add the global component to your App.vue:

<notifications />

**Config**
 - vue: ^3.0.0 => 3.0.11
 - @kyvg/vue3-notification: ^2.2.5 => 2.2.5

**Comment by kyvg** [comment]
I think it can be fixed by [babel-plugin-proposal-optional-chaining plugin]( https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) in 2.2.x version. So I change target to es6 and there are no more optional chaining in 2.3.0 version
